# -*- coding: utf-8 -*-
"""Route classified M3 payment JSON to the matching bank automation.

This module intentionally does not implement bank UI automation itself. It
feeds the JSON generated by step4_extract.py into the existing bank projects
under Desktop, then launches their current entrypoints.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Iterable

try:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
except Exception:
    pass


ROOT = Path(__file__).resolve().parent
DESKTOP = Path.home() / "Desktop"
FINANCE_HOME = Path(os.getenv("FINANCE_HOME", DESKTOP / "财务"))
DEFAULT_GATEWAY_HOME = DESKTOP / "网关"
RUNTIME_DIR = ROOT / "runtime"
CURRENT_DIR = RUNTIME_DIR / "current"
BANK_BATCH_DIR = RUNTIME_DIR / "bank_batches"
BANK_FORMS_DIR = RUNTIME_DIR / "bank_forms"
BANK_RUN_DIR = RUNTIME_DIR / "bank_runs"
LEGACY_BANK_BATCH_DIR = ROOT / "bank_batches"
LEGACY_BANK_FORMS_DIR = ROOT / "bank_forms"
MAX_GATEWAY_IMAGES = 5
M3_IMAGE_KEYS = ("M3抓取详情截图", "M3合同付款列表截图")
M3_INFO_KEYS = (
    "M3报表名称",
    "M3报表入口",
    "M3报表序号",
    "M3列表行键",
    "申请人",
    "申请部门",
    "申请日期",
    "申请金额",
    "付款方式",
    "合同名称",
    "合同名称链接文本",
    "合同名称链接",
    "采购合同名称",
    "采购合同链接",
    "采购合同申请说明",
    "采购合同支付单号",
    "M3跳过制单",
    "M3跳过原因",
    "合同编号",
    "收款单位名称",
    "付款单位名称",
    "开户银行",
    "银行账户",
    "合同金额",
    "累计申请金额",
    "申请说明",
    "类别",
    "M3列表行文本",
)

BANK_ALIASES = {
    "招商银行": ("招商银行", "招行", "CMB"),
    "兴业银行": ("兴业银行", "兴业", "CIB"),
    "中国农业银行": ("中国农业银行", "农业银行", "农行", "ABC"),
    "中国银行": ("中国银行", "中行", "BOC"),
}

BANK_QUEUE_FILES = {
    "招商银行": "招行.json",
    "兴业银行": "兴业银行.json",
    "中国农业银行": "农业银行.json",
    "中国银行": "中国银行.json",
}

def first_existing_path(*candidates: Path) -> Path:
    fallback = candidates[0]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return fallback


BANK_ROOTS = {
    "招商银行": first_existing_path(FINANCE_HOME / "招行" / "招行制单", DESKTOP / "招行制单"),
    "兴业银行": first_existing_path(FINANCE_HOME / "兴业" / "兴业制单", DESKTOP / "兴业制单"),
    "中国农业银行": first_existing_path(FINANCE_HOME / "农业" / "农业银行", DESKTOP / "农业银行"),
    "中国银行": first_existing_path(FINANCE_HOME / "中行" / "中国银行", DESKTOP / "中国银行"),
}

# 全局银行自动化锁（跨项目）：与"来参缘定时调拨"互斥。模块在 财务\公共\locks\
# bank_automation_lock.py；在真实启动银行子进程前持有，结束后 finally 释放。
# dry-run / M3_DISABLE_BANK_INVOCATION / 路由验证 等"不开银行"的路径不会走到这里。
_GLOBAL_BANK_LOCK_DIR = FINANCE_HOME / "公共" / "locks"


def _global_bank_lock_module():
    """Lazy-import 财务\\公共\\locks\\bank_automation_lock。

    模块不存在或 import 失败时返回 None；调用方应记录一条警告但**不要**因此
    放行真实银行子进程（M3 是 fail-closed 设计）。
    """
    if not _GLOBAL_BANK_LOCK_DIR.exists():
        return None
    if str(_GLOBAL_BANK_LOCK_DIR) not in sys.path:
        sys.path.insert(0, str(_GLOBAL_BANK_LOCK_DIR))
    try:
        import bank_automation_lock as mod  # type: ignore
    except Exception:
        return None
    return mod


# fail-closed 退出码：全局银行自动化锁被另一个 owner（如来参缘定时调拨）持有。
# 区别于已有的 124（超时）/ 125（M3_DISABLE_BANK_INVOCATION 阻断）和各子项目的
# 1/2/9/13 业务码。生产路由不在收到该码后自动重试。
BANK_ROUTE_GLOBAL_LOCK_BUSY_EXIT_CODE = 126

CMB_FORM_DIR = BANK_ROOTS["招商银行"] / "M3直供合同付款数据获取"
CMB_SCRIPT = BANK_ROOTS["招商银行"] / "招行" / "skills" / "制单单账号单笔转账skill" / "制单.py"
CIB_ROOT = BANK_ROOTS["兴业银行"]
ABC_SCRIPT = BANK_ROOTS["中国农业银行"] / "skills" / "单笔转账" / "open_browser.py"
BOC_SCRIPT = BANK_ROOTS["中国银行"] / "open_boc.py"

# M3 农行路由的 USBHub 物理口。这里是 UKey 物理口映射，不参与付款银行判定；
# M3 主路由仍由 step4_extract.py 的付款单位/付款银行规则决定。
ABC_M3_UKEY_PORT_BY_PAYER: tuple[tuple[str, str], ...] = (
    ("蒙特", "11"),
    ("蒙选", "13"),
    ("巡鲜", "14"),
    ("得鲜", "15"),
)
ABC_M3_OK_SERVO_PORT_DEFAULT = "30"


class RouteError(RuntimeError):
    """A fail-closed routing error before any bank program is opened."""


def compact(value: object) -> str:
    return "".join(str(value or "").split())


def canonical_bank(value: object) -> str:
    text = compact(value)
    if not text:
        return ""
    upper_text = text.upper()
    for bank_name, aliases in BANK_ALIASES.items():
        for alias in aliases:
            if compact(alias).upper() in upper_text:
                return bank_name
    return ""


def python_exe() -> str:
    configured = os.getenv("BANK_ROUTE_PYTHON", "").strip()
    if configured:
        return configured
    local_appdata = os.getenv("LOCALAPPDATA", "")
    py312 = Path(local_appdata) / "Programs" / "Python" / "Python312" / "python.exe"
    if py312.exists():
        return str(py312)
    return sys.executable


def truthy_env(name: str, default: bool = True) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() not in {"0", "false", "no", "off"}


def env_float(name: str, default: float) -> float:
    raw = os.getenv(name, "").strip()
    if not raw:
        return default
    try:
        return float(raw)
    except ValueError:
        return default


# 银行子进程统一超时（秒）。默认 900s，避免某个银行 GUI 卡死后堵死
# 24 小时调度循环。设为 <=0 表示禁用超时（仅在明确知道风险时使用）。
BANK_ROUTE_PROCESS_TIMEOUT_DEFAULT = 900.0


def bank_route_process_timeout() -> float | None:
    seconds = env_float(
        "BANK_ROUTE_PROCESS_TIMEOUT_SECONDS", BANK_ROUTE_PROCESS_TIMEOUT_DEFAULT
    )
    if seconds is None or seconds <= 0:
        return None
    return seconds


# 银行子进程超时退出码（区别于子项目自身的 1/2/9/13 等业务退出码）。
BANK_ROUTE_TIMEOUT_EXIT_CODE = 124
# 安全阻断退出码：M3_DISABLE_BANK_INVOCATION=1 时，在非 dry-run 真实调用前 fail-closed，
# 不 spawn 任何银行子进程；区别于超时码 124 与各子项目 1/2/9/13 等业务退出码。
BANK_ROUTE_INVOCATION_DISABLED_EXIT_CODE = 125


def bank_invocation_disabled() -> bool:
    return truthy_env("M3_DISABLE_BANK_INVOCATION", False)


def cleanup_after_timeout(bank: str) -> None:
    """超时后尽力做对应银行的清理；招行/兴业无专用清理函数，仅说明依赖子项目 finally/外层清理。"""
    canonical = canonical_bank(bank) or bank
    try:
        if canonical == "中国农业银行":
            cleanup_abc_runtime_after_failure()
        elif canonical == "中国银行":
            cleanup_boc_runtime_after_failure()
        else:
            print(
                f"[{canonical or '未知银行'}] 子流程超时：无专用清理函数，"
                "依赖该银行子项目自身的 finally 收尾与外层 cleanup_after_automation；"
                "本调度层不新增强制关闭/all-off 操作以免误伤。"
            )
    except Exception as exc:  # noqa: BLE001 - 清理是 best-effort，不能因清理异常掩盖超时
        print(f"[{canonical or '未知银行'}] 超时清理过程中出现异常（忽略）：{type(exc).__name__}: {exc}")


def require_m3_screenshots() -> bool:
    return truthy_env("M3_REQUIRE_SCREENSHOTS", True)


def production_mode() -> bool:
    return truthy_env("M3_PRODUCTION_MODE", False)


def run_mode() -> str:
    return "production" if production_mode() else "verification"


def mode_label(dry_run: bool = False) -> str:
    if dry_run:
        return "路由验证"
    return {"production": "生产", "verification": "测试/验证"}.get(run_mode(), run_mode())


BANK_MODE_ENV = {
    "招商银行": {
        "production": {"ZHIDAN_TEST_MODE": "0"},
        "verification": {"ZHIDAN_TEST_MODE": "1"},
    },
    "兴业银行": {
        "production": {"CIB_ALLOW_SUBMIT": "1"},
        "verification": {},
    },
    "中国银行": {
        "production": {"BOC_ENABLE_ORDER_SUBMIT": "1"},
        "verification": {"BOC_ENABLE_ORDER_SUBMIT": "0"},
    },
}

BANK_MODE_UNSET = {
    "招商银行": {
        "production": ("USB_HUB_FORCE_PORT", "ZHIDAN_ALLOW_FORCE_USB_PORT", "M3_CMB_USB_PORT"),
        "verification": (),
    },
    "兴业银行": {
        "production": (),
        "verification": ("CIB_ALLOW_SUBMIT",),
    },
    "中国银行": {
        "production": (),
        "verification": ("BOC_ENABLE_ORDER_SUBMIT",),
    },
}

BANK_EXIT_HINTS = {
    "招商银行": {
        2: "招行路由预检、表单字段或 U 盾匹配失败",
        9: "招行经办点击后的结果需要核对",
        13: "招行经办后出现风险提示或警告",
    },
    "兴业银行": {
        1: "兴业填单或提交前流程失败，需看兴业截图/日志确认具体字段",
        2: "兴业路由预检或 JSON 字段失败",
    },
    "中国农业银行": {
        1: "农行填单流程失败，需看农行截图/日志确认具体字段",
        2: "农行路由预检或 JSON 字段失败",
    },
    "中国银行": {
        1: "中行填单或首步提交流程失败，需看中行截图/日志确认具体字段",
        2: "中行路由预检或 JSON 字段失败",
    },
}


def apply_bank_mode_env(bank: str, env: dict[str, str]) -> dict[str, str]:
    bank = canonical_bank(bank) or bank
    mode = run_mode()
    for key in BANK_MODE_UNSET.get(bank, {}).get(mode, ()):
        env.pop(key, None)
    env.update(BANK_MODE_ENV.get(bank, {}).get(mode, {}))
    return env


def describe_exit_code(bank: str, code: object, *, dry_run: bool = False) -> str:
    try:
        code_int = int(code)
    except (TypeError, ValueError):
        return ""
    if code_int == 0:
        return ""
    bank_name = canonical_bank(bank) or str(bank or "未知银行")
    if code_int == BANK_ROUTE_INVOCATION_DISABLED_EXIT_CODE:
        return (
            f"安全开关阻断：M3_DISABLE_BANK_INVOCATION=1，未启动 {bank_name} 子进程"
            f"（退出码 {code_int}）"
        )
    if code_int == BANK_ROUTE_TIMEOUT_EXIT_CODE:
        return f"{bank_name} 子流程超时被强制结束（退出码 {code_int}，非业务退出码）"
    if code_int == BANK_ROUTE_GLOBAL_LOCK_BUSY_EXIT_CODE:
        return (
            f"全局银行自动化锁被另一个 owner 持有（如来参缘定时调拨），"
            f"未启动 {bank_name} 子进程（退出码 {code_int}，非业务退出码，"
            "需人工稍后重试，不要自动强抢）"
        )
    hint = BANK_EXIT_HINTS.get(bank_name, {}).get(code_int, f"{bank_name} 子流程异常退出")
    return f"{mode_label(dry_run)}失败：{hint}（退出码 {code_int}）"


def gateway_script() -> Path | None:
    gateway_home = Path(os.getenv("CODEX_GATEWAY_HOME", str(DEFAULT_GATEWAY_HOME)))
    candidate = gateway_home / "scripts" / "run_and_report.py"
    return candidate if candidate.exists() else None


def report_script() -> Path | None:
    gateway_home = Path(os.getenv("CODEX_GATEWAY_HOME", str(DEFAULT_GATEWAY_HOME)))
    candidate = gateway_home / "scripts" / "report_to_codex.py"
    return candidate if candidate.exists() else None


def wrap_with_gateway(args: list[str], cwd: Path, *, report_errors: bool = True) -> list[str]:
    if not report_errors or not truthy_env("BANK_ROUTE_REPORT_ERRORS", True):
        return args
    script = gateway_script()
    if script is None:
        return args
    return [
        python_exe(),
        str(script),
        "--project-path",
        str(cwd),
        "--title",
        os.getenv("BANK_ROUTE_REPORT_TITLE", "M3银行制单失败"),
        "--source",
        os.getenv("BANK_ROUTE_REPORT_SOURCE", "M3 bank_route"),
        "--cwd",
        str(cwd),
        "--",
        *args,
    ]


def read_json(path: Path) -> object:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)


def normalize_amount(value: object) -> str:
    return str(value or "").replace(",", "").replace("，", "").strip()


def first_value(form: dict, *keys: str) -> str:
    for key in keys:
        value = form.get(key)
        if str(value or "").strip():
            return str(value).strip()
    return ""


def normalize_usb_port(value: object, env_name: str) -> str:
    port = str(value or "").strip()
    if not port:
        return ""
    if not port.isdigit() or not 1 <= int(port) <= 30:
        raise RouteError(f"{env_name} 必须是 1-30 的数字端口，当前为: {port}")
    return str(int(port))


def resolve_m3_abc_ukey_port(form: dict) -> str:
    """Return the ABC UKey physical USBHub port for an M3-origin payer.

    This is deliberately separate from bank routing. It only answers:
    "this record is already routed to ABC; which physical ABC UKey should be
    powered?" Unknown payer means fail-closed before opening the bank.
    """
    override = (
        os.getenv("M3_ABC_UKEY_USB_PORT", "")
        or os.getenv("ABC_USB_HUB_UKEY_PORT", "")
    )
    override_port = normalize_usb_port(override, "M3_ABC_UKEY_USB_PORT/ABC_USB_HUB_UKEY_PORT")
    if override_port:
        return override_port

    payer_norm = compact(first_value(form, "付款单位名称", "付款单位"))
    if not payer_norm:
        return ""
    for keyword, port in ABC_M3_UKEY_PORT_BY_PAYER:
        if compact(keyword) in payer_norm:
            return port
    return ""


def resolve_m3_abc_ok_servo_port() -> str:
    """Return the external ABC OK clicker port for M3 ABC runs."""
    return normalize_usb_port(
        os.getenv("M3_ABC_OK_SERVO_USB_PORT", "")
        or os.getenv("ABC_OK_SERVO_USB_PORT", "")
        or ABC_M3_OK_SERVO_PORT_DEFAULT,
        "M3_ABC_OK_SERVO_USB_PORT/ABC_OK_SERVO_USB_PORT",
    )


def _truthy_form_value(form: dict, *keys: str) -> bool:
    """从 form 里任一 key 读出"显式真值"。

    用于 bank_form 内的布尔类强制开关（如 `CMB_REQUIRE_LOGIN_ACCOUNT_SELECTION` /
    `招行强制选择登录名`）。覆盖 bool / 数字 / 常见真值字符串（"1" / "true" /
    "yes" / "on" / "是" / "真"），并对其它字符串显式返回 False，避免空串或
    `"false"` 被误判为真。
    """
    for key in keys:
        if key not in form:
            continue
        raw = form.get(key)
        if isinstance(raw, bool):
            if raw:
                return True
            continue
        if isinstance(raw, (int, float)):
            if raw != 0:
                return True
            continue
        if isinstance(raw, str):
            if raw.strip().lower() in {"1", "true", "yes", "on", "是", "真"}:
                return True
    return False


# ===== 招行付款方账号尾号推导 =====
# M3/OA 抓出来的「付款账号 / 付款方账号 / 付方账号 / 付款账户 / 付款账户账号」字段
# 用于推导招行单笔转账经办页面「付款方账号」下拉里的目标尾号（3 位）。
# 不从收款字段、收款账号、收款开户行、收款银行、支行推导。
_M3_PAYER_ACCOUNT_KEYS: tuple[str, ...] = (
    "付款账号", "付款方账号", "付方账号",
    "付款账户", "付款账户账号",
    "付方账户", "付方账户账号",
    "付款人账号", "付款人账户",
)

# 人工确认的「付款单位关键词 → 招行付款方账号尾号」兜底规则。
# 仅在 form 既没有显式尾号、也没有 M3/OA 付款账号字段时使用；只看付款单位名称
# （`付款单位名称 / 付款单位`），不看任何收款字段。
# 未命中时**保持页面默认**（不写 suffix），绝不猜。
# 默认留空 —— 新增条目必须基于人工核实的「付款单位 → 实际启用的招行 001/002 账号」
# 业务事实，并在 PR 描述里写清来源；不要在仓库中提交未审计的真实账号尾号。
_CMB_PAYER_UNIT_TO_ACCOUNT_SUFFIX: tuple[tuple[str, str], ...] = ()


def _digits_only(value: object) -> str:
    return "".join(ch for ch in str(value or "") if ch.isdigit())


def _account_tail_from_m3_field(text: object, n: int = 3) -> str:
    """从 M3/OA 付款账号字段提取末尾 N 位数字。

    与下游 `ubank_common._payer_account_tail_digits` 同一套切分规则：
    - 按 `,` / `，` 取账号段（防 「账号, 公司名」 里的数字污染）；
    - 账号段数字位数 >= n 才返回末 N 位；否则 fail-closed 返回空串。
    """
    if n <= 0:
        return ""
    s = str(text or "")
    for sep in (",", "，"):
        if sep in s:
            s = s.split(sep, 1)[0]
            break
    digits = _digits_only(s)
    if len(digits) >= n:
        return digits[-n:]
    return ""


def derive_cmb_payer_account_suffix(form: dict, payer_unit: str) -> str:
    """推导招行付款方账号尾号（生产主路径）。

    优先级：
    1. form 显式尾号字段（`招行付款方账号尾号 / CMB_PAYER_ACCOUNT_SUFFIX / CMB付款方账号尾号`）；
    2. M3/OA 付款账号字段（`_M3_PAYER_ACCOUNT_KEYS` 列出的任一）—— 抽末 3 位；
    3. 已人工确认的「付款单位 → 尾号」规则表 `_CMB_PAYER_UNIT_TO_ACCOUNT_SUFFIX`。
    都未命中返回空串，调用方按「不写 suffix，保持页面默认账号」处理。

    输入 `payer_unit` 仅参与第 3 步规则匹配；绝不从收款方任何字段推导。
    """
    explicit = first_value(form, "招行付款方账号尾号", "CMB_PAYER_ACCOUNT_SUFFIX", "CMB付款方账号尾号")
    if explicit and explicit.isdigit():
        return explicit

    for key in _M3_PAYER_ACCOUNT_KEYS:
        raw = form.get(key)
        if raw is None:
            continue
        tail = _account_tail_from_m3_field(raw, 3)
        if tail:
            return tail

    if _CMB_PAYER_UNIT_TO_ACCOUNT_SUFFIX:
        payer_norm = compact(payer_unit)
        if payer_norm:
            for keyword, suffix in _CMB_PAYER_UNIT_TO_ACCOUNT_SUFFIX:
                kw = compact(keyword)
                if kw and kw in payer_norm and suffix.isdigit():
                    return suffix

    return ""


def safe_filename(value: object) -> str:
    text = str(value or "").strip()
    text = re.sub(r'[<>:"/\\|?*]+', "_", text)
    return text or "unknown"


def build_branch_queries(bank_head: str, branch_full: str) -> list[str]:
    bank_head = (bank_head or "").strip()
    branch_full = (branch_full or "").strip()
    if not branch_full:
        return [bank_head] if bank_head else []

    simplified = branch_full
    for token in ("股份有限公司", "有限责任公司", "有限公司", "股份有限", "有限"):
        simplified = simplified.replace(token, "")
    if bank_head:
        simplified = simplified.replace(bank_head, "")
    simplified = simplified.replace("支行", "").replace("分行", "").strip()

    candidates = [
        simplified,
        f"{bank_head}{simplified}" if bank_head and simplified else "",
        bank_head,
        branch_full,
    ]
    result: list[str] = []
    for item in candidates:
        item = item.strip()
        if item and item not in result:
            result.append(item)
    return result


def validate_m3_screenshot_info(form: dict) -> list[str]:
    """Return screenshot contract errors for M3-originated payment information."""
    if not require_m3_screenshots():
        return []

    errors: list[str] = []
    for key, label in (
        ("M3合同付款列表截图", "合同付款列表截图"),
        ("M3抓取详情截图", "付款详情截图"),
    ):
        value = first_value(form, key)
        if not value:
            errors.append(f"缺少{label}")
            continue
        path = Path(value)
        if not path.exists() or not path.is_file():
            errors.append(f"{label}不存在: {value}")
    return errors


def check_bank_project(bank: str) -> None:
    root = BANK_ROOTS.get(bank)
    if root is None:
        raise RouteError(f"未配置银行目录: {bank}")
    if not root.exists():
        raise RouteError(f"银行目录不存在: {root}")
    expected = {
        "招商银行": CMB_SCRIPT,
        "兴业银行": CIB_ROOT / "cib_open_bank" / "main_flow.py",
        "中国农业银行": ABC_SCRIPT,
        "中国银行": BOC_SCRIPT,
    }[bank]
    if not expected.exists():
        raise RouteError(f"银行入口不存在: {expected}")


def normalize_form(form: dict, bank: str) -> dict:
    if not isinstance(form, dict):
        raise RouteError("JSON 顶层必须是对象")

    payment_bank = canonical_bank(bank or form.get("付款银行") or form.get("付款银行原文"))
    if not payment_bank:
        raise RouteError("未识别付款银行，不能启动银行程序")

    account = compact(first_value(form, "收方账号", "acct_no", "银行账户", "收款账号", "收款方账号"))
    payee_name = first_value(form, "收方户名", "acct_name", "收款单位名称", "收款户名", "收款方户名")
    amount = normalize_amount(first_value(form, "金额", "amount", "申请金额", "转账金额"))
    original_amount = amount
    amount_override = normalize_amount(os.getenv("M3_BANK_AMOUNT_OVERRIDE", ""))
    if amount_override:
        amount = amount_override
    receive_bank = first_value(form, "开户银行", "bank", "收款方开户行", "收款银行")
    branch_full = first_value(form, "支行名称", "branch_full", "开户支行", "开户网点")
    purpose = first_value(form, "用途", "purpose", "申请说明", "备注") or "货款"
    ref = first_value(form, "业务参考号", "label", "单据编号", "合同编号")
    payer = first_value(form, "付款单位名称", "付款单位")

    errors: list[str] = []
    if not account:
        errors.append("缺少收款账号")
    elif not account.isdigit():
        errors.append(f"收款账号必须为纯数字: {account}")
    elif not (8 <= len(account) <= 32):
        errors.append(f"收款账号位数异常({len(account)}): {account}")

    if not payee_name:
        errors.append("缺少收款户名")
    if not amount:
        errors.append("缺少金额")
    else:
        try:
            amount_value = float(amount)
        except ValueError:
            errors.append(f"金额不是有效数字: {amount}")
        else:
            if amount_value <= 0:
                errors.append(f"金额必须大于 0: {amount}")
            else:
                # 生产风控可配置上限：M3_MAX_PAYMENT_AMOUNT 默认空＝只做格式校验，
                # 不限额；显式设置且为正数时，超限直接 fail-closed（不启动银行）。
                # 不硬编码任何真实金额上限，仅提供机制。
                max_cap_raw = os.getenv("M3_MAX_PAYMENT_AMOUNT", "").strip()
                if max_cap_raw:
                    try:
                        max_cap = float(normalize_amount(max_cap_raw))
                    except ValueError:
                        errors.append(
                            f"M3_MAX_PAYMENT_AMOUNT 不是有效数字: {max_cap_raw}（请修正或清空该环境变量）"
                        )
                    else:
                        if max_cap > 0 and amount_value > max_cap:
                            errors.append(
                                f"金额 {amount} 超过生产上限 {max_cap_raw}"
                                f"（M3_MAX_PAYMENT_AMOUNT）：fail-closed，不启动银行制单"
                            )

    if not receive_bank:
        errors.append("缺少收款开户银行")
    if payment_bank == "招商银行" and not payer:
        errors.append("招行制单需要付款单位名称来匹配 U 盾端口")
    if payment_bank == "兴业银行" and not branch_full:
        errors.append("兴业制单需要完整支行名称参与指纹和搜索")
    if payment_bank == "中国银行" and not (branch_full or receive_bank):
        errors.append("中行制单需要收款人开户行")
    errors.extend(validate_m3_screenshot_info(form))

    if errors:
        raise RouteError("；".join(errors))

    normalized = dict(form)
    branch_queries = form.get("branch_queries")
    if not isinstance(branch_queries, list) or not all(isinstance(x, str) for x in branch_queries):
        branch_queries = build_branch_queries(receive_bank, branch_full)

    # 招行可选字段：登录名（同一 U-BANK 下挂多账号时用），属于「双账号特殊场景」
    # 能力，**默认不写入 bank_form**：避免普通单账号公司因 form 残留登录名字段
    # 而被下拉候选读取失败卡住。
    #
    # 透传条件（任一即可）：
    #   - 源 form 显式含 CMB_REQUIRE_LOGIN_ACCOUNT_SELECTION=true；
    #   - 源 form 显式含 招行强制选择登录名=true。
    # 满足时把强制开关本身一起镜像写入归一化 bank_form，让下游 制单.py 据此决定
    # 是否注入 CMB_LOGIN_ACCOUNT_NAME；否则原 form 里的登录名字段被丢弃、不参与
    # 归一化输出。
    cmb_login_account_name_raw = first_value(form, "招行登录名", "CMB_LOGIN_ACCOUNT_NAME", "CMB登录名")
    cmb_login_force_enabled = _truthy_form_value(form, "CMB_REQUIRE_LOGIN_ACCOUNT_SELECTION", "招行强制选择登录名")
    if cmb_login_account_name_raw and cmb_login_force_enabled:
        cmb_login_account_name = cmb_login_account_name_raw
    else:
        if cmb_login_account_name_raw and not cmb_login_force_enabled:
            print(
                "[M3 路由] bank_form 含登录名字段，但未设置 CMB_REQUIRE_LOGIN_ACCOUNT_SELECTION=true/"
                "招行强制选择登录名=true，归一化时已丢弃；沿用 U-BANK 默认登录名"
            )
        cmb_login_account_name = ""

    # 招行可选字段：付款方账号下拉（单笔转账经办页面的「付款方账号」），与登录名是
    # 两条独立流程。仅做保留透传 / 由 M3 字段推导尾号，不改路由 / 金额覆盖 /
    # 提交门禁 / U 盾端口。
    #
    # 少数公司同一个 UKey 在登录窗口切换账号（例如来参缘 001/002），此时即使
    # M3 本地账户表带有「付款账号」，也必须禁止把账号末三位继续推导成制单页
    # 付款方账号下拉选择；否则会同时触发两套选择链路。
    # - 完整付款账号文本仅在 form 显式提供时透传，绝不主动从其它字段构造（生产主路径
    #   走 suffix；TEXT 仅供调试 / 兜底）。
    # - SUFFIX 走 derive_cmb_payer_account_suffix：显式字段 → M3 付款账号字段 →
    #   人工确认的付款单位规则；任一未命中返回空串，由调用方保持页面默认账号。
    cmb_disable_payer_account_selection = _truthy_form_value(
        form,
        "CMB_DISABLE_PAYER_ACCOUNT_SELECTION",
        "招行禁用付款方账号选择",
    )
    if cmb_disable_payer_account_selection:
        cmb_payer_account_text = ""
        cmb_payer_account_suffix = ""
    else:
        cmb_payer_account_text = first_value(form, "招行付款方账号", "CMB_PAYER_ACCOUNT_TEXT", "CMB付款方账号")
        cmb_payer_account_suffix = derive_cmb_payer_account_suffix(form, payer)

    normalized.update(
        {
            "付款银行": payment_bank,
            "M3合同付款列表截图": first_value(form, "M3合同付款列表截图"),
            "M3抓取详情截图": first_value(form, "M3抓取详情截图"),
            "付款单位名称": payer,
            "收方账号": account,
            "收方户名": payee_name,
            "开户银行": receive_bank,
            "支行名称": branch_full,
            "金额": amount,
            "原始金额": original_amount if amount_override else form.get("原始金额", ""),
            "金额覆盖来源": "M3_BANK_AMOUNT_OVERRIDE" if amount_override else form.get("金额覆盖来源", ""),
            "用途": purpose,
            "业务参考号": ref,
            "label": ref or form.get("label") or "default",
            "amount": amount,
            "acct_no": account,
            "acct_name": payee_name,
            "bank": receive_bank,
            "branch_full": branch_full,
            "branch_queries": branch_queries,
            "purpose": purpose,
        }
    )
    if cmb_login_account_name:
        normalized["招行登录名"] = cmb_login_account_name
        normalized["CMB_LOGIN_ACCOUNT_NAME"] = cmb_login_account_name
        # 强制开关与值一起镜像写入归一化 bank_form，让下游 制单.py 在未显式 env
        # 注入 CMB_LOGIN_ACCOUNT_NAME 时仍能据此启用登录名选择。
        normalized["CMB_REQUIRE_LOGIN_ACCOUNT_SELECTION"] = True
        normalized["招行强制选择登录名"] = True
    else:
        # 默认归一化输出：删除可能从源 form 浅拷贝过来的登录名/强制开关字段，
        # 避免单账号公司在 bank_form 残留下进入登录名选择路径。
        for _stale_key in (
            "招行登录名",
            "CMB_LOGIN_ACCOUNT_NAME",
            "CMB登录名",
            "CMB_REQUIRE_LOGIN_ACCOUNT_SELECTION",
            "招行强制选择登录名",
        ):
            normalized.pop(_stale_key, None)
    if cmb_payer_account_text:
        normalized["招行付款方账号"] = cmb_payer_account_text
        normalized["CMB_PAYER_ACCOUNT_TEXT"] = cmb_payer_account_text
    if cmb_payer_account_suffix:
        normalized["招行付款方账号尾号"] = cmb_payer_account_suffix
        normalized["CMB_PAYER_ACCOUNT_SUFFIX"] = cmb_payer_account_suffix
    if cmb_disable_payer_account_selection:
        for _stale_key in (
            "招行付款方账号",
            "CMB_PAYER_ACCOUNT_TEXT",
            "CMB付款方账号",
            "招行付款方账号尾号",
            "CMB_PAYER_ACCOUNT_SUFFIX",
            "CMB付款方账号尾号",
            "CMB_PAYER_ACCOUNT_INDEX",
        ):
            normalized.pop(_stale_key, None)
        normalized["CMB_DISABLE_PAYER_ACCOUNT_SELECTION"] = True
        normalized["招行禁用付款方账号选择"] = True
    return normalized


def load_latest_form() -> tuple[dict, Path]:
    route_paths = [
        BANK_FORMS_DIR / "latest_route.json",
        LEGACY_BANK_FORMS_DIR / "latest_route.json",
    ]
    for route_path in route_paths:
        if not route_path.exists():
            continue
        route = read_json(route_path)
        if isinstance(route, dict):
            for key in ("制单JSON", "银行JSON"):
                candidate = route.get(key)
                if candidate and Path(candidate).exists():
                    path = Path(candidate)
                    payload = read_json(path)
                    if isinstance(payload, dict):
                        return payload, path
    for path in (CURRENT_DIR / "bank_form.json", ROOT / "bank_form.json"):
        if not path.exists():
            continue
        payload = read_json(path)
        if not isinstance(payload, dict):
            raise RouteError(f"默认表单 JSON 不是对象: {path}")
        return payload, path
    raise RouteError(f"未找到默认表单 JSON: {CURRENT_DIR / 'bank_form.json'}")


def load_single_form(path_text: str | None) -> tuple[dict, Path]:
    if not path_text:
        return load_latest_form()
    path = Path(path_text)
    if not path.is_absolute():
        path = ROOT / path
    if not path.exists():
        raise RouteError(f"JSON 文件不存在: {path}")
    payload = read_json(path)
    if not isinstance(payload, dict):
        raise RouteError(f"单笔制单 JSON 必须是对象: {path}")
    return payload, path


def queue_path_for_bank(bank: str) -> Path:
    filename = BANK_QUEUE_FILES[bank]
    return BANK_BATCH_DIR / filename


def load_bank_queue(bank: str) -> list[dict]:
    path = queue_path_for_bank(bank)
    if not path.exists():
        legacy_path = LEGACY_BANK_BATCH_DIR / BANK_QUEUE_FILES[bank]
        if legacy_path.exists():
            path = legacy_path
    if not path.exists():
        return []
    payload = read_json(path)
    if isinstance(payload, dict):
        payload = [payload]
    if not isinstance(payload, list):
        raise RouteError(f"银行队列 JSON 必须是数组或对象: {path}")
    result = []
    for index, item in enumerate(payload, start=1):
        if not isinstance(item, dict):
            raise RouteError(f"{path} 第 {index} 条不是对象")
        result.append(item)
    return result


def run_payload_path(bank: str, payload: object) -> Path:
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    ref = ""
    if isinstance(payload, dict):
        ref = first_value(payload, "业务参考号", "label", "单据编号")
    filename = f"{timestamp}_{safe_filename(ref)}.json" if ref else f"{timestamp}.json"
    return BANK_RUN_DIR / BANK_QUEUE_FILES[bank].replace(".json", "") / filename


def create_run_payload(bank: str, payload: object, dry_run: bool) -> Path:
    path = run_payload_path(bank, payload)
    if not dry_run:
        write_json(path, payload)
    return path


def run_process(
    args: list[str],
    cwd: Path,
    env: dict[str, str],
    dry_run: bool,
    *,
    report_errors: bool = True,
    bank: str = "",
) -> int:
    display_args = []
    for arg in args:
        text = str(arg)
        if "\n" in text:
            display_args.append("<inline-python>")
        elif len(text) > 180:
            display_args.append(text[:177] + "...")
        else:
            display_args.append(text)
    cmd_summary = " ".join(display_args)
    print(f"工作目录: {cwd}")
    print("启动命令:", cmd_summary)
    if dry_run:
        print("[dry-run] 未启动银行程序。")
        return 0
    if bank_invocation_disabled():
        canonical = canonical_bank(bank) or bank or "未知银行"
        print(
            f"[安全阻断] M3_DISABLE_BANK_INVOCATION=1，禁止启动真实银行子进程。\n"
            f"        银行: {canonical}\n"
            f"        工作目录: {cwd}\n"
            f"        命令摘要: {cmd_summary}\n"
            f"        退出码: {BANK_ROUTE_INVOCATION_DISABLED_EXIT_CODE}（安全阻断，非业务退出码）"
        )
        return BANK_ROUTE_INVOCATION_DISABLED_EXIT_CODE
    timeout = bank_route_process_timeout()
    if timeout is not None:
        print(f"[守护] 银行子流程超时上限: {timeout:.0f}s（BANK_ROUTE_PROCESS_TIMEOUT_SECONDS）")

    # 全局银行自动化锁：与"来参缘定时调拨"互斥。dry-run / M3_DISABLE_BANK_INVOCATION
    # 已在上面的早退路径里跳过这里，所以现在站在"将要真启动银行子进程"的位置。
    canonical_bank_name = canonical_bank(bank) or bank or "未知银行"
    global_lock_mod = _global_bank_lock_module()
    holds_global_lock = False
    if global_lock_mod is None:
        print(
            "[全局锁][fail-closed] 未找到 财务\\公共\\locks\\bank_automation_lock 模块；"
            f"无法与来参缘定时调拨互斥，不启动 {canonical_bank_name} 子进程。\n"
            f"        退出码: {BANK_ROUTE_GLOBAL_LOCK_BUSY_EXIT_CODE}（全局锁不可用，非业务退出码）"
        )
        return BANK_ROUTE_GLOBAL_LOCK_BUSY_EXIT_CODE
    else:
        try:
            g_action, g_prev = global_lock_mod.acquire(
                owner=global_lock_mod.OWNER_M3_BANK_ROUTE,
                purpose=f"M3银行制单路由 / {canonical_bank_name}",
                run_dir=str(cwd),
            )
        except global_lock_mod.LockBusy as exc:
            print(
                "[全局锁][fail-closed] 全局银行自动化锁被另一个 owner 持有，"
                f"不启动 {canonical_bank_name} 子进程。\n"
                f"        现有 owner: {exc.prev}\n"
                f"        退出码: {BANK_ROUTE_GLOBAL_LOCK_BUSY_EXIT_CODE}（全局锁忙，非业务退出码）"
            )
            return BANK_ROUTE_GLOBAL_LOCK_BUSY_EXIT_CODE
        except global_lock_mod.LockTakeoverFailed as exc:
            print(
                f"[全局锁][fail-closed] stale 全局锁接管失败：{exc}；"
                f"不启动 {canonical_bank_name} 子进程"
            )
            return BANK_ROUTE_GLOBAL_LOCK_BUSY_EXIT_CODE
        else:
            holds_global_lock = True
            if g_action == "stole_stale":
                print(f"[全局锁] 检测到 stale 全局锁并已清理：prev={g_prev}")
            else:
                print(f"[全局锁] 已获取全局银行自动化锁（owner=m3_bank_route）")

    try:
        try:
            completed = subprocess.run(
                wrap_with_gateway(args, cwd, report_errors=report_errors),
                cwd=str(cwd),
                env=env,
                check=False,
                timeout=timeout,
            )
            return int(completed.returncode)
        except subprocess.TimeoutExpired:
            # 子进程已被 subprocess 杀掉（含网关包装层）；银行 GUI/浏览器可能仍
            # 残留，交由对应银行清理函数按命令行/窗口标题收尾。返回固定超时码
            # 124（区别于业务退出码），由上层既有路由规则决定是否重试，
            # 本层不扩大重试、不在超时后盲目重跑可能已提交的制单。
            canonical = canonical_bank(bank) or bank or "未知银行"
            print(
                f"[守护][超时] {canonical} 子流程超过 {timeout:.0f}s 未结束，已强制结束子进程。\n"
                f"        工作目录: {cwd}\n"
                f"        命令摘要: {cmd_summary}\n"
                f"        超时秒数: {timeout:.0f}（BANK_ROUTE_PROCESS_TIMEOUT_SECONDS）\n"
                f"        退出码: {BANK_ROUTE_TIMEOUT_EXIT_CODE}（超时，非业务退出码）"
            )
            cleanup_after_timeout(bank)
            return BANK_ROUTE_TIMEOUT_EXIT_CODE
    finally:
        # 仅释放本进程持有的全局银行自动化锁；owner/pid 不匹配的不动。
        if holds_global_lock and global_lock_mod is not None:
            try:
                if global_lock_mod.release(owner=global_lock_mod.OWNER_M3_BANK_ROUTE):
                    print("[全局锁] 已释放全局银行自动化锁（owner=m3_bank_route）")
                else:
                    print(
                        "[全局锁] 释放全局银行自动化锁 noop（锁文件不属于本进程或已被外部清理）"
                    )
            except Exception as exc:  # noqa: BLE001
                print(f"[全局锁] 释放过程中出现异常（忽略，不掩盖主流程退出码）：{type(exc).__name__}: {exc}")


def abc_usb_hub_all_off() -> None:
    hub_script = (
        FINANCE_HOME
        / "公共"
        / "usbhub"
        / "usbhub"
        / "多口USB控制器软件以及驱动"
        / "hub_ctrl.py"
    )
    if not hub_script.exists():
        print(f"[农行] USBHub 控制脚本不存在，跳过 all-off: {hub_script}")
        return
    com = (
        os.getenv("ABC_USB_HUB_COM", "").strip()
        or os.getenv("USB_HUB_COM", "").strip()
        or "COM3"
    )
    completed = subprocess.run(
        [python_exe(), str(hub_script), "all-off", "--com", com],
        cwd=str(hub_script.parent),
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    if completed.returncode == 0:
        print(f"[农行] USBHub all-off 已执行（{com}）")
    else:
        print(f"[农行] USBHub all-off 失败（{com}，退出码 {completed.returncode}）")


def cleanup_abc_runtime_after_failure() -> None:
    """Close stale ABC browser/script processes and power down the USB hub before retrying."""
    print("[农行] 制单失败，正在关闭农行页面/脚本并准备重跑...")
    ps_script = r"""
$ErrorActionPreference = 'SilentlyContinue'
$currentPid = $PID
Get-CimInstance Win32_Process |
  Where-Object {
    $_.ProcessId -ne $currentPid -and
    (
      (($_.Name -eq 'python.exe' -or $_.Name -eq 'pythonw.exe') -and $_.CommandLine -like '*open_browser.py*') -or
      (($_.Name -eq 'chrome.exe') -and $_.CommandLine -like '*playwright_chromiumdev_profile*')
    )
  } |
  ForEach-Object {
    try { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue } catch {}
  }
Get-Process msedge -ErrorAction SilentlyContinue |
  Where-Object { $_.MainWindowTitle -like '*中国农业银行*' -or $_.MainWindowTitle -like '*农行*' } |
  ForEach-Object {
    try {
      [void]$_.CloseMainWindow()
      Start-Sleep -Milliseconds 800
      if (-not $_.HasExited) { Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue }
    } catch {}
  }
"""
    subprocess.run(
        ["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps_script],
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    if truthy_env("ABC_ROUTE_ALL_OFF_AFTER_FAILURE", True):
        abc_usb_hub_all_off()


def boc_usb_hub_all_off() -> None:
    hub_script = (
        Path(os.getenv("BOC_USBHUB_CTRL_PATH", "").strip())
        if os.getenv("BOC_USBHUB_CTRL_PATH", "").strip()
        else FINANCE_HOME
        / "公共"
        / "usbhub"
        / "usbhub"
        / "多口USB控制器软件以及驱动"
        / "hub_ctrl.py"
    )
    if not hub_script.exists():
        print(f"[中行] USBHub 控制脚本不存在，跳过 all-off: {hub_script}")
        return
    com = (
        os.getenv("BOC_USBHUB_COM", "").strip()
        or os.getenv("USB_HUB_COM", "").strip()
        or "COM3"
    )
    completed = subprocess.run(
        [python_exe(), str(hub_script), "all-off", "--com", com],
        cwd=str(hub_script.parent),
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    if completed.returncode == 0:
        print(f"[中行] USBHub all-off 已执行（{com}）")
    else:
        print(f"[中行] USBHub all-off 失败（{com}，退出码 {completed.returncode}）")


def cleanup_boc_runtime_after_failure() -> None:
    """Close stale BOC browser/script/dialog state and power down USB before retrying."""
    print("[中行] 制单失败，正在关闭中行页面/脚本并准备重跑...")
    ps_script = r"""
$ErrorActionPreference = 'SilentlyContinue'
$currentPid = $PID
Get-CimInstance Win32_Process |
  Where-Object {
    $_.ProcessId -ne $currentPid -and
    (
      (($_.Name -eq 'python.exe' -or $_.Name -eq 'pythonw.exe') -and $_.CommandLine -like '*open_boc.py*') -or
      (($_.Name -eq 'msedge.exe' -or $_.Name -eq 'chrome.exe') -and $_.CommandLine -like '*boc_playwright_*')
    )
  } |
  ForEach-Object {
    try { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue } catch {}
  }

$dialogPatterns = @('*选择证书*', '*Windows 安全*', '*校验用户密码*', '*检验用户密码*', '*U盾*', '*U 盾*', '*USBKey*', '*UKey*', '*温馨提示*', '*常见解决方案*', '*登录失败*', '*Login failed*', '*loginCAFailSolution*')
Get-Process -ErrorAction SilentlyContinue |
  Where-Object {
    $title = $_.MainWindowTitle
    $dialogPatterns | Where-Object { $title -like $_ }
  } |
  ForEach-Object {
    try {
      [void]$_.CloseMainWindow()
      Start-Sleep -Milliseconds 800
      if (-not $_.HasExited) { Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue }
    } catch {}
  }
"""
    subprocess.run(
        ["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps_script],
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    if truthy_env("BOC_ROUTE_ALL_OFF_AFTER_FAILURE", True):
        boc_usb_hub_all_off()



def status_label(status: object) -> str:
    labels = {
        "succeeded": "成功",
        "success": "成功",
        "failed": "失败",
        "dry_run": "验证通过",
        "running": "执行中",
        "seen": "已记录",
    }
    return labels.get(str(status or ""), str(status or "未知"))


def public_record(record: dict) -> dict:
    return {key: value for key, value in record.items() if not key.startswith("_")}


def m3_detail_image_path(form: dict) -> str:
    for key in M3_IMAGE_KEYS:
        image_path = first_value(form, key)
        if image_path and Path(image_path).is_file():
            return image_path
    return ""


def build_m3_status_record(detail: dict, *, dry_run: bool = False) -> dict:
    form = detail.get("form") if isinstance(detail.get("form"), dict) else {}
    bank = str(detail.get("bank") or form.get("付款银行") or "").strip()
    normalized: dict = {}
    normalize_error = ""
    try:
        normalized = normalize_form(form, bank) if form else {}
    except Exception as exc:
        normalize_error = str(exc)
        normalized = dict(form)

    status = str(detail.get("status") or "unknown")
    error = str(detail.get("error") or normalize_error or "").strip()
    problem = error or str(detail.get("reason") or "").strip()
    m3_info = {key: form.get(key, normalized.get(key, "")) for key in M3_INFO_KEYS}
    m3_info = {key: value for key, value in m3_info.items() if str(value or "").strip()}
    mapped_fields = {
        "付款银行": normalized.get("付款银行", bank),
        "收款账号": normalized.get("收方账号", first_value(form, "收方账号", "acct_no", "银行账户")),
        "收款户名": normalized.get("收方户名", first_value(form, "收方户名", "acct_name", "收款单位名称")),
        "开户行": normalized.get("开户银行", first_value(form, "开户银行", "bank")),
        "支行": normalized.get("支行名称", first_value(form, "支行名称", "branch_full")),
        "金额": normalized.get("金额", first_value(form, "金额", "amount", "申请金额")),
        "原始金额": normalized.get("原始金额", first_value(form, "原始金额", "申请金额")),
        "用途": normalized.get("用途", first_value(form, "用途", "purpose")),
    }
    mapped_fields = {key: value for key, value in mapped_fields.items() if str(value or "").strip()}
    return {
        "付款银行": mapped_fields.get("付款银行") or bank or "未知银行",
        "业务参考号": detail.get("ref") or normalized.get("业务参考号") or normalized.get("label") or first_value(form, "业务参考号", "label", "单据编号", "合同编号"),
        "状态": status_label(status),
        "退出码": detail.get("exit_code"),
        "问题": problem,
        "运行模式": mode_label(dry_run),
        "验证模式": bool(dry_run) or not production_mode(),
        "M3原始信息": m3_info,
        "制单字段": mapped_fields,
        "_image_path": m3_detail_image_path(form),
    }


def create_m3_contact_sheets(records: list[dict], output_dir: Path) -> list[str]:
    image_records = [record for record in records if str(record.get("_image_path") or "").strip()]
    if not image_records:
        return []
    try:
        from PIL import Image, ImageDraw, ImageFont, ImageOps

        output_dir.mkdir(parents=True, exist_ok=True)
        columns = 2
        per_sheet = 10
        thumb_size = (900, 528)
        padding = 24
        label_height = 48
        font = ImageFont.load_default()
        outputs: list[str] = []
        for sheet_no, start in enumerate(range(0, len(image_records), per_sheet), start=1):
            chunk = image_records[start : start + per_sheet]
            rows = (len(chunk) + columns - 1) // columns
            tile_width = thumb_size[0] + padding * 2
            tile_height = thumb_size[1] + label_height + padding * 2
            sheet = Image.new("RGB", (columns * tile_width, rows * tile_height), "white")
            draw = ImageDraw.Draw(sheet)
            for idx, record in enumerate(chunk):
                source = Image.open(str(record["_image_path"])).convert("RGB")
                thumb = ImageOps.contain(source, thumb_size)
                col = idx % columns
                row = idx // columns
                x0 = col * tile_width + padding
                y0 = row * tile_height + padding
                title = f"{record.get('付款银行')} {record.get('业务参考号')} {record.get('状态')}"
                draw.text((x0, y0), title[:120], fill=(0, 0, 0), font=font)
                sheet.paste(thumb, (x0, y0 + label_height))
            output = output_dir / f"m3_status_contact_sheet_{sheet_no:02d}.jpg"
            sheet.save(output, "JPEG", quality=88, optimize=True)
            outputs.append(str(output))
            if len(outputs) >= MAX_GATEWAY_IMAGES:
                break
        return outputs
    except Exception as exc:
        print(f"[M3通知] 生成 M3 联页图失败: {exc}")
        images: list[str] = []
        for record in image_records:
            image_path = str(record.get("_image_path") or "")
            if image_path and image_path not in images:
                images.append(image_path)
        return images[:MAX_GATEWAY_IMAGES]


def _append_existing_image(target: list[str], image_path: object) -> None:
    text = str(image_path or "").strip()
    if not text or text in target:
        return
    if not Path(text).is_file():
        return
    target.append(text)


def select_notification_images(
    *,
    status: str,
    records: list[dict],
    image_paths: list[str] | None,
) -> list[str]:
    """Choose outbound images for finance-facing M3 reports.

    Success is intentionally quiet: attach exactly one M3 detail/current
    screenshot so finance can confirm the voucher source. Failure carries
    more evidence: the failure/current screenshot first, then contact sheets
    or individual M3 detail screenshots up to the gateway limit.
    """
    normalized_status = str(status or "").strip().lower()
    success = normalized_status in {"success", "succeeded"}
    selected: list[str] = []

    if success:
        for image_path in image_paths or []:
            _append_existing_image(selected, image_path)
            if selected:
                return selected[:1]
        for record in records:
            _append_existing_image(selected, record.get("_image_path"))
            if selected:
                return selected[:1]
        return []

    for image_path in image_paths or []:
        _append_existing_image(selected, image_path)
        if len(selected) >= MAX_GATEWAY_IMAGES:
            return selected[:MAX_GATEWAY_IMAGES]

    contact_sheet_paths = create_m3_contact_sheets(
        records,
        RUNTIME_DIR / "notifications" / time.strftime("%Y%m%d_%H%M%S"),
    )
    for image_path in contact_sheet_paths:
        _append_existing_image(selected, image_path)
        if len(selected) >= MAX_GATEWAY_IMAGES:
            return selected[:MAX_GATEWAY_IMAGES]

    for record in records:
        _append_existing_image(selected, record.get("_image_path"))
        if len(selected) >= MAX_GATEWAY_IMAGES:
            break
    return selected[:MAX_GATEWAY_IMAGES]


def finance_facing_message(*, status: str, records: list[dict], summary: str, dry_run: bool, image_count: int) -> str:
    success = str(status or "").strip().lower() in {"success", "succeeded"}
    mode = "验证模式" if dry_run or not production_mode() else "生产制单模式"
    refs = [str(record.get("业务参考号") or "").strip() for record in records]
    refs = [ref for ref in refs if ref]
    banks = sorted({str(record.get("付款银行") or "").strip() for record in records if str(record.get("付款银行") or "").strip()})
    ref_text = "、".join(refs[:3]) + (" 等" if len(refs) > 3 else "")
    bank_text = "、".join(banks) if banks else "未识别银行"
    if success:
        image_text = "已附 1 张 M3 详情图，供核对单据和付款信息。" if image_count else "未附截图，请查看本机运行记录核对。"
        boundary = "本次只完成验证/路由，不产生真实制单。" if dry_run else "本次只进入银行待审核/待复核队列，不自动复核、授权或付款。"
        if not records:
            return f"{mode}完成：本轮 M3 抽取完成，没有新增/变更需要制单的银行队列记录。{image_text}{boundary}"
        return f"{mode}成功：{bank_text} {ref_text or '本轮记录'} 已处理完成。{image_text}{boundary}"

    reasons = []
    for record in records:
        problem = str(record.get("问题") or "").strip()
        ref = str(record.get("业务参考号") or "").strip()
        bank = str(record.get("付款银行") or "").strip()
        if problem:
            prefix = " / ".join([item for item in (bank, ref) if item])
            reasons.append(f"{prefix}: {problem}" if prefix else problem)
    if not reasons:
        reasons.append(summary.strip() or "未提供明确失败原因，请查看日志。")
    image_text = f"已附 {image_count} 张流程/现场图。" if image_count else "未附截图。"
    manual_hint = "如需人工处理，请先让 Codex CLI 暂停 M3 监控；处理完后再让 Codex CLI 继续 M3 监控。"
    return f"{mode}失败：{image_text}主要原因：{'；'.join(reasons[:3])}。{manual_hint}"


def finance_error_json_line(
    *,
    stage: str,
    reason: str,
    impact: str,
    next_action: str,
    bank: str = "",
    doc: str = "",
    safe_state: str = "",
) -> str:
    """Return a gateway-readable structured finance error line.

    The gateway consumes lines prefixed with FINANCE_ERROR_JSON= and turns them
    into short Feishu messages. Keep this payload business-facing: no paths,
    commands, env names, passwords, or raw logs.
    """
    payload = {
        "stage": str(stage or "").strip(),
        "reason": str(reason or "").strip(),
        "impact": str(impact or "").strip(),
        "next_action": str(next_action or "").strip(),
        "bank": str(bank or "").strip(),
        "doc": str(doc or "").strip(),
        "safe_state": str(safe_state or "").strip(),
    }
    payload = {key: value for key, value in payload.items() if value}
    return "FINANCE_ERROR_JSON=" + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))


def finance_error_json_from_records(
    *,
    status: str,
    records: list[dict],
    summary: str,
    dry_run: bool,
    default_stage: str = "M3自动制单",
) -> str:
    success = str(status or "").strip().lower() in {"success", "succeeded", "dry_run"}
    if success:
        return ""

    refs = [str(record.get("业务参考号") or "").strip() for record in records]
    refs = [ref for ref in refs if ref]
    banks = sorted({str(record.get("付款银行") or "").strip() for record in records if str(record.get("付款银行") or "").strip()})
    problems = [str(record.get("问题") or "").strip() for record in records if str(record.get("问题") or "").strip()]
    reason = "；".join(problems[:3]) or str(summary or "").strip() or "本轮失败，未提供明确原因。"
    joined_reason = f"{reason} {summary or ''}"
    bank_text = "、".join(banks) if banks else "未识别银行"
    doc_text = "、".join(refs[:3]) + (" 等" if len(refs) > 3 else "")

    if "未识别付款银行" in joined_reason:
        return finance_error_json_line(
            stage="M3付款银行识别",
            reason=reason,
            impact="该记录已隔离，未写入任何银行制单队列，未启动银行客户端。",
            next_action="请财务确认付款单位对应的付款银行；确认后由技术同事补充路由规则，再恢复 M3 监控。",
            bank="未识别银行",
            doc=doc_text,
            safe_state="未操作银行，未产生待审核或待复核记录。",
        )
    if "全局银行自动化锁" in joined_reason or "锁" in joined_reason and "持有" in joined_reason:
        return finance_error_json_line(
            stage="银行启动前安全互斥",
            reason=reason,
            impact="本次未启动银行子流程，避免与另一项银行任务同时占用 UKey。",
            next_action="请等待当前银行任务结束后重试；不要强制抢锁。",
            bank=bank_text,
            doc=doc_text,
            safe_state="未新增自动复核、授权或付款。",
        )

    if dry_run or not production_mode():
        impact = "当前是验证模式，本轮不产生真实制单，不进入银行待审核或待复核队列。"
        safe_state = "验证模式未真实提交，未自动复核、授权或付款。"
    else:
        impact = "本轮失败记录已停止，需要按提示人工核对是否已进入银行待审核或待复核队列。"
        safe_state = "系统不会自动复核、授权或最终付款；如提示可能已提交，请人工核对银行待审核或待复核队列。"
    return finance_error_json_line(
        stage=default_stage,
        reason=reason,
        impact=impact,
        next_action="如需人工处理，请先让 Codex CLI 暂停 M3 监控；处理完后再让 Codex CLI 继续 M3 监控。",
        bank=bank_text,
        doc=doc_text,
        safe_state=safe_state,
    )


def notify_m3_status_report(
    *,
    title: str,
    status: str,
    details: list[dict],
    summary: str,
    context: str,
    source: str,
    dry_run: bool = False,
    log_file: str = "",
    image_paths: list[str] | None = None,
) -> dict:
    script = report_script()
    if script is None:
        print("[M3通知] 网关 report_to_codex.py 不存在，跳过飞书通知")
        return {"attempted": False, "ok": False, "reason": "gateway report script missing"}

    records = [build_m3_status_record(detail, dry_run=dry_run) for detail in details]
    notify_image_paths = select_notification_images(status=status, records=records, image_paths=image_paths)
    finance_message = finance_facing_message(
        status=status,
        records=records,
        summary=summary,
        dry_run=dry_run,
        image_count=len(notify_image_paths),
    )
    structured_error = finance_error_json_from_records(
        status=status,
        records=records,
        summary=summary,
        dry_run=dry_run,
        default_stage="M3银行路由/制单",
    )
    payload = {
        "给财务同事看的结论": finance_message,
        "汇总": summary,
        "模式": mode_label(dry_run),
        "M3图片": (
            "成功仅附 1 张 M3 详情图"
            if str(status or "").strip().lower() in {"success", "succeeded"}
            else f"失败附 {len(notify_image_paths)} 张流程/现场图"
        ),
        "明细": [public_record(record) for record in records],
    }
    cmd = [
        python_exe(),
        str(script),
        "--project-path",
        str(ROOT),
        "--title",
        title,
        "--status",
        status,
        "--error",
        "\n".join([item for item in (summary, structured_error) if item]),
        "--context",
        context,
        "--log",
        json.dumps(payload, ensure_ascii=False, indent=2),
        "--source",
        source,
    ]
    if log_file:
        cmd.extend(["--log-file", log_file])
    for image_path in notify_image_paths:
        cmd.extend(["--image-path", image_path])
    proc = subprocess.run(
        cmd,
        cwd=str(ROOT),
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True,
        check=False,
    )
    if proc.stdout:
        print(proc.stdout.strip())
    if proc.stderr:
        print(proc.stderr.strip())
    skipped = "report skipped:" in (proc.stdout or "")
    print(f"[M3通知] 飞书最终通知退出码: {proc.returncode}")
    return {
        "attempted": not skipped,
        "skipped": skipped,
        "ok": proc.returncode == 0,
        "returncode": proc.returncode,
        "image_count": 0 if skipped else len(notify_image_paths),
    }


def base_env() -> dict[str, str]:
    env = os.environ.copy()
    env.setdefault("PYTHONUTF8", "1")
    env.setdefault("PYTHONIOENCODING", "utf-8")
    env.setdefault("PYTHONDONTWRITEBYTECODE", "1")
    env.setdefault("CODEX_GATEWAY_HOME", str(DEFAULT_GATEWAY_HOME))
    env.setdefault("BANK_ROUTE_REPORT_ERRORS", "1")
    return env


def run_cmb(forms: list[dict], dry_run: bool) -> int:
    check_bank_project("招商银行")
    for index, form in enumerate(forms, start=1):
        normalized = normalize_form(form, "招商银行")
        print(f"\n[招行] 第 {index}/{len(forms)} 笔: {normalized.get('label')}")
        if dry_run:
            print(f"[dry-run] 将写入: {CMB_FORM_DIR / 'bank_form.json'}")
        else:
            write_json(CMB_FORM_DIR / "bank_form.json", normalized)
        env = apply_bank_mode_env("招商银行", base_env())
        cmb_usb_port = os.getenv("M3_CMB_USB_PORT", "7").strip()
        if run_mode() == "verification" and cmb_usb_port:
            env["USB_HUB_FORCE_PORT"] = cmb_usb_port
            env["ZHIDAN_ALLOW_FORCE_USB_PORT"] = "1"
        print(f"[招行] 运行模式: {mode_label(dry_run)}")
        code = run_process(
            [python_exe(), str(CMB_SCRIPT)],
            BANK_ROOTS["招商银行"],
            env,
            dry_run,
            bank="招商银行",
        )
        if code != 0:
            return code
    return 0


CIB_INLINE_RUNNER = r"""
import json
import os
import sys
from pathlib import Path

from cib_open_bank.main_flow import run_transfer_flow
from cib_open_bank.runtime import all_off_usb_hub_ports, set_screenshot_prefix
from cib_open_bank.windows import close_bank_windows, dismiss_ukey_notice

payload = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
transfers = payload if isinstance(payload, list) else [payload]
production = os.getenv("M3_PRODUCTION_MODE", "").strip().lower() in {"1", "true", "yes", "on"}
fill_only = not production
if production:
    os.environ["CIB_ALLOW_SUBMIT"] = "1"
else:
    os.environ.pop("CIB_ALLOW_SUBMIT", None)
failures = 0
for index, transfer in enumerate(transfers, start=1):
    prefix = f"m3_{index:02d}_"
    print("\n" + "#" * 60)
    print(f"开始 M3 兴业制单第 {index}/{len(transfers)} 笔: {transfer.get('label')}")
    print("#" * 60)
    try:
        print(f"[兴业] 运行模式: {'生产' if production else '测试/验证'} fill_only={fill_only}")
        run_transfer_flow(transfer=transfer, fill_only=fill_only, screenshot_prefix=prefix)
    except Exception as exc:
        failures += 1
        print(f"[兴业] 第 {index} 笔失败: {type(exc).__name__}: {exc}")
    finally:
        set_screenshot_prefix("")
        close_bank_windows()
        all_off_usb_hub_ports()
        dismiss_ukey_notice(wait_seconds=5)

raise SystemExit(1 if failures else 0)
"""


def run_cib(forms: list[dict], dry_run: bool) -> int:
    check_bank_project("兴业银行")
    normalized = [normalize_form(form, "兴业银行") for form in forms]
    payload_path = create_run_payload("兴业银行", normalized, dry_run)
    print(f"\n[兴业] 本次载荷: {payload_path}")
    env = apply_bank_mode_env("兴业银行", base_env())
    print(f"[兴业] 运行模式: {mode_label(dry_run)}")
    return run_process(
        [python_exe(), "-c", CIB_INLINE_RUNNER, str(payload_path)],
        CIB_ROOT,
        env,
        dry_run,
        bank="兴业银行",
    )


def run_abc(forms: list[dict], dry_run: bool) -> int:
    check_bank_project("中国农业银行")
    normalized = [normalize_form(form, "中国农业银行") for form in forms]
    args = [python_exe(), str(ABC_SCRIPT)]
    max_attempts = 1 + (0 if dry_run or not truthy_env("ABC_ROUTE_RETRY_ON_FAILURE", True) else 1)

    failures: list[tuple[int, int]] = []
    for index, form in enumerate(normalized, start=1):
        payload_path = create_run_payload("中国农业银行", form, dry_run)
        env = apply_bank_mode_env("中国农业银行", base_env())
        env["M3_TRANSFER_DATA_DIR"] = str(ROOT)
        env["ABC_USB12_PREPARE"] = "true"
        abc_ukey_port = resolve_m3_abc_ukey_port(form)
        if not abc_ukey_port:
            print(
                "[农行][fail-closed] 未配置该付款单位的农行 UKey 物理口："
                f"{form.get('付款单位名称') or form.get('付款单位') or '<空>'}。"
                "请补 USBHub 物理口映射，或本轮显式设置 M3_ABC_UKEY_USB_PORT。"
            )
            failures.append((index, 2))
            continue
        try:
            abc_ok_servo_port = resolve_m3_abc_ok_servo_port()
        except RouteError as exc:
            print(f"[农行][fail-closed] {exc}")
            failures.append((index, 2))
            continue
        env["ABC_USB_HUB_UKEY_PORT"] = abc_ukey_port
        env["ABC_OK_SERVO_USB_PORT"] = abc_ok_servo_port
        env["ABC_USB_HUB_PORTS"] = f"{abc_ukey_port},{abc_ok_servo_port}"
        env["ABC_USB_HUB_EXACT_PORTS"] = "true"
        env.setdefault("ABC_USB_CLOSE_AUTO_HOME_TAB", "true")
        env.setdefault("ABC_KEEP_BROWSER_OPEN", "false")
        env["ABC_OK_SERVO_AFTER_KB_PASSWORD"] = "false"
        env["ABC_OK_SERVO_AFTER_SUBMIT"] = "false"
        if run_mode() == "production" and not dry_run:
            # 农行也是制单项目：生产模式下与招行/兴业/中行一样进入正常制单链
            # （仍单条/逐条），由以下 ABC_* 门禁依次完成 提交→收款账户位数确认→
            # 交易信息确认→交易K宝密码→交易K宝密码提交后触发物理 OK；完成后停在
            # 银行待审核/待复核队列，脚本不自动复核、授权或最终付款。
            env["ABC_ALLOW_SUBMIT_ONCE"] = "true"
            env["ABC_CONFIRM_SUBMIT_MODAL_ONCE"] = "true"
            env["ABC_CONFIRM_TRADE_INFO_ONCE"] = "true"
            env["ABC_TRANSFER_KB_PASSWORD_AFTER_TRADE"] = "true"
            env["ABC_OK_SERVO_ENABLE"] = "true"
            env["ABC_OK_SERVO_AFTER_TRANSFER_KB_PASSWORD"] = "true"
        else:
            # 测试/验证模式（含路由 dry-run）：保持 fill-only，绝不开启
            # 提交/确认/物理 OK 生产门禁，且不沿用外部环境里的同名变量。
            for _abc_gate in (
                "ABC_ALLOW_SUBMIT_ONCE",
                "ABC_CONFIRM_SUBMIT_MODAL_ONCE",
                "ABC_CONFIRM_TRADE_INFO_ONCE",
                "ABC_TRANSFER_KB_PASSWORD_AFTER_TRADE",
                "ABC_OK_SERVO_ENABLE",
                "ABC_OK_SERVO_AFTER_TRANSFER_KB_PASSWORD",
            ):
                env.pop(_abc_gate, None)
        env.pop("TRANSFER_BATCH_PATH", None)
        env["TRANSFER_DATA_PATH"] = str(payload_path)

        print(f"\n[农行] 第 {index}/{len(normalized)} 笔: {form.get('label') or form.get('业务参考号') or '<未知>'}")
        print(f"[农行] 本次单笔载荷: {payload_path}")
        print(f"[农行] USBHub: UKey={abc_ukey_port} 口，外置 OK={abc_ok_servo_port} 口")
        code = 0
        for attempt in range(1, max_attempts + 1):
            if max_attempts > 1:
                print(f"[农行] 第 {index}/{len(normalized)} 笔开始第 {attempt}/{max_attempts} 次完整流程")
            code = run_process(
                args,
                BANK_ROOTS["中国农业银行"],
                env,
                dry_run,
                report_errors=(attempt == max_attempts),
                bank="中国农业银行",
            )
            if not dry_run and code not in (
                BANK_ROUTE_INVOCATION_DISABLED_EXIT_CODE,
                BANK_ROUTE_GLOBAL_LOCK_BUSY_EXIT_CODE,
            ):
                abc_usb_hub_all_off()
            if code == 0:
                break
            if code in (
                BANK_ROUTE_INVOCATION_DISABLED_EXIT_CODE,
                BANK_ROUTE_GLOBAL_LOCK_BUSY_EXIT_CODE,
            ):
                print(
                    f"[农行] 第 {index}/{len(normalized)} 笔未启动银行子进程（退出码 {code}）："
                    "这是安全阻断/全局锁忙，不自动重试、不执行 USBHub all-off，避免影响正在运行的其它银行流程。"
                )
                break
            if code == BANK_ROUTE_TIMEOUT_EXIT_CODE:
                # 超时灰区：可能已提交进银行待审核/待复核队列但脚本未正常退出。
                # 为避免重复制单，超时码 124 一律不自动重试，保留为失败，
                # 由 monitor 记录 failed，需人工核对后再决定是否重跑。
                print(
                    f"[农行] 第 {index}/{len(normalized)} 笔超时（退出码 {code}）："
                    "超时不自动重试（可能已提交进待审核/待复核队列的灰区，自动重跑会重复制单）；"
                    "已保留为失败，请人工核对农行待审核/待复核队列后再决定是否重跑。"
                )
                break
            if attempt < max_attempts:
                print(f"[农行] 第 {index}/{len(normalized)} 笔第 {attempt} 次失败（退出码 {code}），将关闭页面并重跑一次。")
                cleanup_abc_runtime_after_failure()
                time.sleep(3)
        if code != 0:
            failures.append((index, code))

    if failures:
        print(
            "[农行] 失败笔数: "
            + ", ".join(f"{index}(退出码 {code})" for index, code in failures)
        )
        return 1
    return 0


def run_boc(forms: list[dict], dry_run: bool) -> int:
    check_bank_project("中国银行")
    max_attempts = 1 + (0 if dry_run or not truthy_env("BOC_ROUTE_RETRY_ON_FAILURE", True) else 1)
    retry_wait_seconds = max(0.0, env_float("BOC_ROUTE_RETRY_WAIT_SECONDS", 15.0))
    between_items_seconds = max(0.0, env_float("BOC_ROUTE_BETWEEN_ITEMS_SECONDS", 15.0))
    failures: list[tuple[int, int]] = []
    for index, form in enumerate(forms, start=1):
        normalized = normalize_form(form, "中国银行")
        print(f"\n[中行] 第 {index}/{len(forms)} 笔: {normalized.get('label')}")
        env = apply_bank_mode_env("中国银行", base_env())
        env.update(
            {
                "BOC_ENABLE_TRANSFER_FILL": "1",
                "BOC_CLOSE_ON_FINISH": "1",
                "BOC_USBHUB_POWER_ON_START": "1",
                "BOC_USBHUB_ALL_OFF_ON_FINISH": "1",
                "BOC_PAYEE_NAME": normalized["收方户名"],
                "BOC_PAYEE_ACCOUNT": normalized["收方账号"],
                "BOC_PAYEE_BANK": normalized.get("支行名称") or normalized["开户银行"],
                "BOC_PAYEE_BANK_CODE": "",
                "BOC_PAYMENT_AMOUNT": normalized["金额"],
            }
        )
        env.setdefault("BOC_USBHUB_SETTLE_SECONDS", os.getenv("BOC_ROUTE_USBHUB_SETTLE_SECONDS", "12"))
        code = 0
        for attempt in range(1, max_attempts + 1):
            if max_attempts > 1:
                print(f"[中行] 第 {index}/{len(forms)} 笔开始第 {attempt}/{max_attempts} 次完整流程")
            code = run_process(
                [python_exe(), str(BOC_SCRIPT)],
                BANK_ROOTS["中国银行"],
                env,
                dry_run,
                report_errors=(attempt == max_attempts),
                bank="中国银行",
            )
            if not dry_run and code not in (
                BANK_ROUTE_INVOCATION_DISABLED_EXIT_CODE,
                BANK_ROUTE_GLOBAL_LOCK_BUSY_EXIT_CODE,
            ):
                boc_usb_hub_all_off()
            if code == 0:
                break
            if code in (
                BANK_ROUTE_INVOCATION_DISABLED_EXIT_CODE,
                BANK_ROUTE_GLOBAL_LOCK_BUSY_EXIT_CODE,
            ):
                print(
                    f"[中行] 第 {index}/{len(forms)} 笔未启动银行子进程（退出码 {code}）："
                    "这是安全阻断/全局锁忙，不自动重试、不执行 USBHub all-off，避免影响正在运行的其它银行流程。"
                )
                break
            if code == BANK_ROUTE_TIMEOUT_EXIT_CODE:
                # 超时灰区：可能已提交进银行待审核/待复核队列但脚本未正常退出。
                # 为避免重复制单，超时码 124 一律不自动重试，保留为失败，
                # 由 monitor 记录 failed，需人工核对后再决定是否重跑。
                print(
                    f"[中行] 第 {index}/{len(forms)} 笔超时（退出码 {code}）："
                    "超时不自动重试（可能已提交进待审核/待复核队列的灰区，自动重跑会重复制单）；"
                    "已保留为失败，请人工核对中行待审核/待复核队列后再决定是否重跑。"
                )
                break
            if attempt < max_attempts:
                print(f"[中行] 第 {index}/{len(forms)} 笔第 {attempt} 次失败（退出码 {code}），将关闭页面并重跑一次。")
                cleanup_boc_runtime_after_failure()
                if retry_wait_seconds:
                    print(f"[中行] 等待 {retry_wait_seconds:g} 秒，让 UKey/浏览器控件释放后再重跑。")
                    time.sleep(retry_wait_seconds)
        if code != 0:
            failures.append((index, code))
        if not dry_run and index < len(forms) and between_items_seconds:
            print(f"[中行] 第 {index}/{len(forms)} 笔结束，等待 {between_items_seconds:g} 秒后进入下一笔。")
            time.sleep(between_items_seconds)
    if failures:
        print(
            "[中行] 失败笔数: "
            + ", ".join(f"{index}(退出码 {code})" for index, code in failures)
        )
        return 1
    return 0


def run_bank_forms(bank: str, forms: Iterable[dict], dry_run: bool = False) -> int:
    bank = canonical_bank(bank)
    if not bank:
        raise RouteError("未识别付款银行")
    form_list = list(forms)
    if not form_list:
        print(f"[跳过] {bank} 队列为空")
        return 0
    dispatch = {
        "招商银行": run_cmb,
        "兴业银行": run_cib,
        "中国农业银行": run_abc,
        "中国银行": run_boc,
    }
    return dispatch[bank](form_list, dry_run)


def parse_bank_option(value: str) -> str:
    bank = canonical_bank(value)
    if not bank:
        raise argparse.ArgumentTypeError(f"不支持的银行: {value}")
    return bank


def run_single_cli(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="运行最新或指定 JSON 对应的单笔银行制单程序")
    parser.add_argument("json_path", nargs="?", help="单笔 bank_form JSON；不填则使用 latest_route/bank_form")
    parser.add_argument("--bank", type=parse_bank_option, help="手动指定付款银行")
    parser.add_argument("--dry-run", action="store_true", help="只检查和打印，不启动银行程序")
    args = parser.parse_args(argv)

    try:
        form, source = load_single_form(args.json_path)
        bank = args.bank or canonical_bank(form.get("付款银行") or form.get("付款银行原文"))
        normalized = normalize_form(form, bank)
        print(f"数据来源: {source}")
        print(f"付款银行: {normalized['付款银行']}")
        print(f"业务参考号: {normalized.get('业务参考号')}")
        return run_bank_forms(normalized["付款银行"], [normalized], dry_run=args.dry_run)
    except (RouteError, OSError, json.JSONDecodeError) as exc:
        print(f"[终止] {exc}")
        return 2


def run_batch_cli(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="按 bank_batches 中的队列运行银行制单程序")
    parser.add_argument("--bank", "-b", type=parse_bank_option, action="append", help="只运行指定银行，可重复")
    parser.add_argument("--all", action="store_true", help="运行所有非空银行队列")
    parser.add_argument("--limit", type=int, default=0, help="每家银行最多运行前 N 笔，0 表示不限制")
    parser.add_argument("--dry-run", action="store_true", help="只检查和打印，不启动银行程序")
    args = parser.parse_args(argv)

    banks = args.bank or list(BANK_QUEUE_FILES)
    if not args.bank and not args.all:
        print("未指定 --bank，默认扫描所有非空银行队列。")

    try:
        failed = False
        for bank in banks:
            forms = load_bank_queue(bank)
            if args.limit > 0:
                forms = forms[: args.limit]
            if not forms:
                print(f"[跳过] {bank} 队列为空: {queue_path_for_bank(bank)}")
                continue
            print(f"\n准备运行 {bank}: {len(forms)} 笔，队列 {queue_path_for_bank(bank)}")
            code = run_bank_forms(bank, forms, dry_run=args.dry_run)
            if code != 0:
                print(f"[失败] {bank} 退出码: {code}")
                failed = True
                break
        return 1 if failed else 0
    except (RouteError, OSError, json.JSONDecodeError) as exc:
        print(f"[终止] {exc}")
        return 2
